Meditech control panel software: /Volumes/John Doe/Development Projects/Meditech SciFi/SourcesRepositories/chipkit_serial_pi/Meditech_ChipKitControlPanel/Meditech_ChipKitControlPanel.pde File Reference
Meditech_ChipKitControlPanel.pde File Reference
meditech ChipKit control panel main application
#include <AlphaLCD.h>
#include <Streaming.h>
#include "LCD.h"
#include "Analog.h"
#include "StringsGlobals.h"
#include "Version.h"
#include "Globals.h"
#include "Temperature.h"
#include <SoftPWMServo.h>
#include "LCDTemplates.h"
#include "DebugStrings.h"
#include "CommandProcessor.h"
#include "ParserErrors.h"
Functions
AlphaLCD lcd (11, 12, 13)
Display class instance.
void setup ()
Initialisation method.
void loop (void)
Main loop method.
void updateDisplay (int id, void *tptr)
Periodically update the display.
void checkSerial ()
Control the presence of data from the serial interface.
void tempMonitor ()
Update the internal temperature from the sensor and update the display.
void showTemp ()
shows the actual internal temperature on the top right corner.
uint32_t isLidStatusChanged (uint32_t currentTime)
Callback function from the list status change hardware interrupt.
uint32_t fanSpeedRegulation (uint32_t currentTime)
Callback function from the fan cooler speed regulation interrupt.
void welcome ()
Welcome message shown at device power-on.
void message (String m)
Display a string on the LCD at the cursor position.
void error (String m, int x, int y)
Display an error message at the specified cursor coordinates.
void error (String m)
Display an error message at the cursor position.
void message (String m, int x, int y)
Display a string on the LCD at the specified cursor coordinates.
void testStatusLED ()
Show the status led blinking for a cycle to test that all are working.
void testFanSpeed ()
Variable fan speed test cycle.
void setFanSpeed (float temp)
Set the fan speed based on the actual temperature.
int setFanSpeed (int freq)
Set the fan speed at the desired PWM frequency.
void debug (String msg)
Serial debugging function.
int readline (int readch, char *buffer, int len)
Read a full line buffer from serial.
void parser ()
Parses the serial input for control command.
int nextCommandSeparator (int startChar)
Search the position for next command separator.
int nextFieldSeparator (int startChar)
Search the position for next field separator starting from a position.
int charsToInt (int startChar, int numChars)
Convert a string to integer.
String charsToString (int startChar)
Convert a portion of the char array command string to string.
long charsToLong (int startChar, int numChars)
Convert a string to long integer.
float charsToFloat (int startChar, int numChars)
Convert a string to floating point.
boolean isFieldSeparator (char test)
check for separator character
void syntaxCheck (int errCode)
Append the error code to the master response message string.
void appendResponse (String message)
Append the string to the response message string.
void appendResponse (char message)
Append the character to the response message string.
void appendResponse (int message)
Append the integer to the response message string.
void appendResponse (long int message)
Append the long integer to the response message string.
void appendResponse (float message)
Append the float to the response message string.
void ackMaster ()
Acknowledge the master caller when a command parsing has been completed.
void strFloat (float val, unsigned int precision)
Convert a floating value to string with the specified precision.
bool setStethoscopeStatus (int startChar)
Set the stethoscope status flag and initialises the display parameters if needed.
bool setECGStatus (int startChar)
Set the ECG status flag and initialises the display parameters if needed.
bool setPressureStatus (int startChar)
Set the bood pressure status flag and initialises the display parameters if needed.
bool setBodyTempStatus (int startChar)
Set the body temperature status flag and initialises the display parameters if needed.
bool setHeartBeatStatus (int startChar)
Set the heart beat status flag and initialises the display parameters if needed.
Variables
Temperature internalTemp
Internal temperature sensor class instance.
int pValue = 0
Initial potentiometer value.
volatile boolean lidStatus
Current lid status. The variable is declared volatile as it is used by the IRQ callback function too.
int updateDispalyTaskID
The update display task id (assigned on setup)
command cmd
Parser command structure.
static char cmdData [1024]
Unparsed Command String.
Detailed Description
meditech ChipKit control panel main application
Definition in file Meditech_ChipKitControlPanel.pde.
Function Documentation
void ackMaster ()
Acknowledge the master caller when a command parsing has been completed.
Definition at line 1081 of file Meditech_ChipKitControlPanel.pde.
References parseCommand::message.
Referenced by parser().
                  {
   Serial1 << cmd.message << endl;
 }
void appendResponse (String message)
Append the string to the response message string.
Every new step of the parser that needs to be mentioned to the connected master updates the response string. The string should be sent when the parser exits for any condition.
Note
The reponse string is NOT verbose as it should be managed faster and efficiently by the master. Every new message parameter added to the response string is separated by a RESPONSE_SEPARATOR character.
Parameters
message The response message to be added, usually a single-character elment or an error code
Definition at line 1000 of file Meditech_ChipKitControlPanel.pde.
References parseCommand::message, and RESPONSE_SEPARATOR.
Referenced by parser(), and syntaxCheck().
{
   cmd.message.concat(RESPONSE_SEPARATOR);
   cmd.message.concat(message);
 }
void appendResponse (char message)
Append the character to the response message string.
Every new step of the parser that needs to be mentioned to the connected master updates the response string. The string should be sent when the parser exits for any condition.
Note
The reponse string is NOT verbose as it should be managed faster and efficiently by the master. Every new message parameter added to the response string is separated by a RESPONSE_SEPARATOR character.
Parameters
message The response message to be added, usually a single-character elment or an error code
Definition at line 1018 of file Meditech_ChipKitControlPanel.pde.
References parseCommand::message, and RESPONSE_SEPARATOR.
{
   cmd.message.concat(RESPONSE_SEPARATOR);
   cmd.message.concat(message);
 }
void appendResponse (int message)
Append the integer to the response message string.
Every new step of the parser that needs to be mentioned to the connected master updates the response string. The string should be sent when the parser exits for any condition.
Note
The reponse string is NOT verbose as it should be managed faster and efficiently by the master. Every new message parameter added to the response string is separated by a RESPONSE_SEPARATOR character.
Parameters
message The response message to be added, usually a single-character elment or an error code
Definition at line 1036 of file Meditech_ChipKitControlPanel.pde.
References parseCommand::message, and RESPONSE_SEPARATOR.
{
   cmd.message.concat(RESPONSE_SEPARATOR);
   cmd.message.concat(message);
 }
void appendResponse (long int message)
Append the long integer to the response message string.
Every new step of the parser that needs to be mentioned to the connected master updates the response string. The string should be sent when the parser exits for any condition.
Note
The reponse string is NOT verbose as it should be managed faster and efficiently by the master. Every new message parameter added to the response string is separated by a RESPONSE_SEPARATOR character.
Parameters
message The response message to be added, usually a single-character elment or an error code
Definition at line 1054 of file Meditech_ChipKitControlPanel.pde.
References parseCommand::message, and RESPONSE_SEPARATOR.
{
   cmd.message.concat(RESPONSE_SEPARATOR);
   cmd.message.concat(message);
 }
void appendResponse (float message)
Append the float to the response message string.
Every new step of the parser that needs to be mentioned to the connected master updates the response string. The string should be sent when the parser exits for any condition.
Note
The reponse string is NOT verbose as it should be managed faster and efficiently by the master. Every new message parameter added to the response string is separated by a RESPONSE_SEPARATOR character.
Parameters
message The response message to be added, usually a single-character elment or an error code
Definition at line 1072 of file Meditech_ChipKitControlPanel.pde.
References parseCommand::message, and RESPONSE_SEPARATOR.
{
   cmd.message.concat(RESPONSE_SEPARATOR);
   cmd.message.concat(message);
 }
float charsToFloat (int startChar, int numChars)
Convert a string to floating point.
Parameters
startChar initial character in the command string
numChars number of characters composing the number
Returns
The converted floating value
Definition at line 947 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
{
   int i;
   float res = 0;
   String extract = "";
   for (i = 0; i < numChars; i++)
     extract.concat(cmdData[i + startChar]);
   res = extract.toFloat();
   return res;
 }
int charsToInt (int startChar, int numChars)
Convert a string to integer.
Parameters
startChar initial character in the command string
numChars number of characters composing the number
Returns
The converted interger value
Definition at line 844 of file Meditech_ChipKitControlPanel.pde.
References charsToLong().
Referenced by parser().
{
   int res = 0;
   res = (int)charsToLong(startChar, numChars);
   return res;
 }
long charsToLong (int startChar, int numChars)
Convert a string to long integer.
Parameters
startChar initial character in the command string
numChars number of characters composing the number
Returns
The converted long interger value
Definition at line 927 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
Referenced by charsToInt().
{
   int i;
   long res = 0;
   String extract = "";
   for (i = 0; i < numChars; i++)
     extract.concat(cmdData[i + startChar]);
   res = extract.toInt();
   return res;
 }
String charsToString (int startChar)
Convert a portion of the char array command string to string.
This function does not include the number of characters as it is a variable lenght. The command strings are identified by the initial and final '"' string delimiter character, so the function search for the first delimiter and queue charaters in the destination string until the second string delimiter is not found.
If no string delimiters are found the cycle stops when reach the CMD_MSGLEN character count limit; in this case an empty string is returned. If only the first string delimiter is found the function returns the entire right string command character array.
Warning
As the character '"' is used as string delimiter it should not be used as part of the string. Use the ''' instead.
Parameters
startChar initial character in the command string
Returns
The converted interger value
Definition at line 870 of file Meditech_ChipKitControlPanel.pde.
References cmdData, MAX_CMD_LEN, and STRING_DELIMITER.
Referenced by parser().
{
   String temp = "";
   int i = 0;
   bool inString = false;
   // ========================================== FIRST STRING DELIMITER
   // Search for the first string delimiter
   while(!inString) {
     // Check if the current char points to the first string delimiter
     if(cmdData[i + startChar] == STRING_DELIMITER) {
       i++;
       inString = true;
     } // String delimieter found ?
     else {
       // Check for the end of string
       if(cmdData[i + startChar] == MAX_CMD_LEN) {
         // Exit with an empty string
         return "";
       } // Reached the end of the command string ?
       else {
         i++;
       } // Search to next character
     } // Delimiter not found
   } // While out of string
   // ========================================== UNTIL SECOND STRING DELIMITER
   // Collect the string characters
   while(inString) {
     // Check if the current char points to the first string delimiter
     if(cmdData[i + startChar] == STRING_DELIMITER) {
       inString = false;
     } // String delimieter found ?
     else {
       // Check for the end of string
       if(cmdData[i + startChar] == MAX_CMD_LEN) {
         // Exit with the collected string
         return temp;
       } // Reached the end of the command string ?
       else {
         // Collect the character in the string and move to next
         temp.concat(cmdData[i + startChar]);
         i++;
       } // Search to next character
     } // Delimiter not found
   } // While inside the string
   // Found both delimiters and collected the string.
   return temp;
 }
void checkSerial ()
Control the presence of data from the serial interface.
When data are detected on the serial buffer the parser function is launched to process the command.
Definition at line 171 of file Meditech_ChipKitControlPanel.pde.
References cmdData, parseCommand::commandLength, MAX_CMD_LEN, parser(), and readline().
Referenced by loop().
                    {
   int nChar;
   cmd.commandLength = readline(Serial1.read(), cmdData, MAX_CMD_LEN);
   // If the line ends the program launch the parser.
   if (cmd.commandLength > 0) {
     #ifdef __DEBUG
     Serial1 << "Received: >" << cmdData << "<" << endl;
     #endif
     parser(); // parse the command
   }
 }
void debug (String msg)
Serial debugging function.
Definition at line 405 of file Meditech_ChipKitControlPanel.pde.
References DEBG_PREFIX.
Referenced by parser().
{
 #ifdef __DEBUG
   Serial1 << DEBG_PREFIX << "> " << msg << endl;
 #endif
 }
void error (String m, int x, int y)
Display an error message at the specified cursor coordinates.
The error message is shown for a LCDERROR_DELAY milliseconds. After the timeout expires the screen is not cleared so the next steps should be managed by the program flow. It is expected that error messages are shown in a calling code that manages the error conditions.
Parameters
m the message string
x the cursor column zero based
y the row number zero based
Definition at line 282 of file Meditech_ChipKitControlPanel.pde.
References LCDERROR_DELAY, and message().
{
   message(m, x, y);
   delay(LCDERROR_DELAY);
 }
void error (String m)
Display an error message at the cursor position.
The error message is shown for a LCDERROR_DELAY milliseconds. After the timeout expires the screen is not cleared so the next steps should be managed by the program flow. It is expected that error messages are shown in a calling code that manages the error conditions.
Parameters
m the string message
Definition at line 297 of file Meditech_ChipKitControlPanel.pde.
References LCDERROR_DELAY, and message().
                      {
   message(m);
   delay(LCDERROR_DELAY);
 }
uint32_t fanSpeedRegulation (uint32_t currentTime)
Callback function from the fan cooler speed regulation interrupt.
As the interrupt triggers periodically a new temperature reading is done and the PWM fan cooler speed is set accordingly.
Definition at line 227 of file Meditech_ChipKitControlPanel.pde.
References FAN_SPEED, MAX_FANSPEED, MAX_TEMP, MIN_FANSPEED, MIN_TEMP, TEMP_OFFSET, TEMP_SENSOR, and UPDATE_FAN_SPEED_TIMEOUT.
Referenced by setup().
{
   float temp;
   int pwmSpeed;
   temp = (((analogRead(TEMP_SENSOR) / 1024) * 5) * 100) - TEMP_OFFSET;
   pwmSpeed = map(temp, MIN_TEMP, MAX_TEMP, MIN_FANSPEED, MAX_FANSPEED);
   SoftPWMServoPWMWrite(FAN_SPEED, pwmSpeed);
   // Restart the timer
   return (currentTime + CORE_TICK_RATE * UPDATE_FAN_SPEED_TIMEOUT);
 }
boolean isFieldSeparator (char test)
check for separator character
Parameters
test the character to test
Returns
true if test is equal else returns false.
Definition at line 966 of file Meditech_ChipKitControlPanel.pde.
References FIELD_SEPARATOR.
Referenced by parser().
{
   #ifdef __DEBUG
   Serial1 << "Field separator=" << test << endl;
   #endif
   if (test == FIELD_SEPARATOR)
       return true;
   else
       return false;
 }
uint32_t isLidStatusChanged (uint32_t currentTime)
Callback function from the list status change hardware interrupt.
When the lid status switch changes (pinned to the LIDSTATUS pin) the attached interrupt calls this callback that simply invert the lidStatus state of the boolean variable. After the function has been exectued the timer is restarted.
Definition at line 213 of file Meditech_ChipKitControlPanel.pde.
References LID_OPEN_TIMEOUT, LIDSTATUS, and lidStatus.
Referenced by setup().
{
     lidStatus = digitalRead(LIDSTATUS);
     // Restart the timer
     return (currentTime + CORE_TICK_RATE * LID_OPEN_TIMEOUT);
 }
AlphaLCD lcd (11 , 12 , 13)
Display class instance.
Referenced by loop(), message(), parser(), setup(), showTemp(), and welcome().
void loop (void)
Main loop method.
The main application loop is interrupted by the lid open status generating a high priority alarm. Also the internal temperature is checked periodically to set the fan speed to the correct value.
When serial data are present (a command waiting from the PI main) the data are parsed as needed.
Definition at line 143 of file Meditech_ChipKitControlPanel.pde.
References _LID_OPEN, checkSerial(), lcd(), LCDTOPROW, LIDCLOSED, lidStatus, and message().
                 {
   // Check if the lid is open
   if(lidStatus == LIDCLOSED) {
     checkSerial();
   }
   else {
     // Show the error message
     lcd.clear();
     message(_LID_OPEN, 5, LCDTOPROW);
   }
 }
void message (String m)
Display a string on the LCD at the cursor position.
Parameters
m the message string
Definition at line 266 of file Meditech_ChipKitControlPanel.pde.
References lcd().
Referenced by error(), loop(), message(), and parser().
{
   lcd.print(m);
 }
void message (String m, int x, int y)
Display a string on the LCD at the specified cursor coordinates.
Parameters
m the string message
x the cursor column zero based
y the row number zero based
Definition at line 309 of file Meditech_ChipKitControlPanel.pde.
References lcd(), and message().
{
   lcd.setCursor(x, y);
   message(m);
 }
int nextCommandSeparator (int startChar)
Search the position for next command separator.
This function is used for complex commands to find the first starting point of a new command (if exist) The function starts from the startChar and ends when a command separator is found. If none exists, the function ends when a null character is encountered.
Parameters
startChar initial character in the command string
Returns
the position of the first command separator (if any) or the last position before the end of the command string.
Definition at line 795 of file Meditech_ChipKitControlPanel.pde.
References CMD_SEPARATOR, and cmdData.
Referenced by parser().
{
   int i = 0;
   while (cmdData[startChar + i] != '\0') {
     if (cmdData[startChar + i] == CMD_SEPARATOR)
       return startChar + i;
     i++;
   }
   return i;
 }
int nextFieldSeparator (int startChar)
Search the position for next field separator starting from a position.
This function is used to find the first next field separator starting from the specified position. It should be used instead of the isFieldSeparator() boolean check when the last processed field has a variable length (i.e. strings)
Note
The use of this function may generate errors so it is best practice after a value is returned to check it in the calling program with isFieldSeparator() function.
Parameters
startChar initial character in the command string
Returns
the position of the first command separator (if any) or the last reached position (end of string)
Definition at line 821 of file Meditech_ChipKitControlPanel.pde.
References cmdData, and FIELD_SEPARATOR.
Referenced by parser().
{
   int i = 0;
   while (cmdData[startChar + i] != '\0') {
     #ifdef __DEBUG
     Serial1 << "nextFieldSeparator(" << startChar << ") i = " << i << " char = " << cmdData[startChar + i] << endl;
     #endif
     if (cmdData[startChar + i] == FIELD_SEPARATOR)
       return startChar + i;
     i++;
   }
   return i;
 }
void parser ()
Parses the serial input for control command.
If the syntax checker doesn't recognize any valid command strings are ignored and discharged. Every command is a single-character, case sensitive. All the characters recognised as a command are listed in the CMD_CHARACTERS constant; when the parser starts only those commands included in this string and stored in the cBuff character buffer can be accepted as valid commands, else the string portion is not processed until the next command separator (or the end of the string if there is only one command or it is the last).
Counters and indexes. The initaliasation matters are these are the correct points for the parser recursive process.
Single-character commands array
The template class instance
The field counter to fill the class fields description
The max number of fields of the template class
Definition at line 454 of file Meditech_ChipKitControlPanel.pde.
References ackMaster(), appendResponse(), charsToInt(), charsToString(), LCDTemplates::cleanDisplay(), CMD_CHARLEN, CMD_DISPLAY, CMD_ENABLE, CMD_INFO, CMD_LCDTEMPLATE, CMD_SEPARATOR, CMD_TEST, cmdData, COMMAND_BODYTEMP_PARAMERROR, COMMAND_ECG_PARAMERROR, COMMAND_HEARTBEAT_PARAMERROR, COMMAND_MISSINGSEPARATOR, COMMAND_OK, COMMAND_OUT_OF_RANGE, COMMAND_PRESSURE_PARAMERROR, COMMAND_STETHOSCOPE_PARAMERROR, COMMAND_WRONG_TEMPLATE, parseCommand::commandLength, LCDTemplates::createDisplay(), debug(), LCDTemplates::id, parseCommand::intValue, isFieldSeparator(), lcd(), LCDCHARS, LCDROWS, MAX_TEMPLATES, parseCommand::message, message(), nextCommandSeparator(), nextFieldSeparator(), PARM_FIELDID_LEN, PARM_INTEGER_LEN, PARSER_SUBCOMMAND_UNKNOWN, S_BODYTEMP, S_ECG, S_HEARTBEAT, S_PRESSURE, S_STETHOSCOPE, setBodyTempStatus(), setECGStatus(), setHeartBeatStatus(), setPressureStatus(), setStethoscopeStatus(), parseCommand::stringValue, parseCommand::subcommand, syntaxCheck(), and LCDTemplates::updateDisplay().
Referenced by checkSerial().
               {
   int i = 0, k = 0, j = 0, value;
   char c[] = { 'E', 'D', 'L', 'G', 'I', 'T', 'R', 'P', 'r', '\0' };
   LCDTemplates mTemplate(lcd);
   int z = 0;
   int maxFields = 0;
   // Initialises the command structure
 //  cmdData[0] = '\0';
   cmd.message = "";
   // Load the command string coming from serial in the character array
 //  while (Serial1.available() > 0)
 //      cmdData[i++] = (char)Serial1.read();
   // Add the closing command character
   cmdData[cmd.commandLength] = CMD_SEPARATOR;
 //  cmdData[i] = '\0';
   i = cmd.commandLength + 1;
   debug(cmdData);
   // Here we start processing recursively the array until the end.
   while (k < i) {
     // If a command separator is found, anyway we have already finished processing
     // the command (including eventually an error condition). So the character is
     // skipped until a new command start is not found.
     // Using this strategy it is possible to include between two commands or anywhere
     // outside a valid sequence any kind of comment.
     if (cmdData[k] == CMD_SEPARATOR)
       k++;
     // Search for a valid command character and when found set the processing flags.
     // Else generates an error condition.
     for (j = 0; j < CMD_CHARLEN; j++) {
       // Process the current command character
       if (c[j] == cmdData[k]) {
         // Found a matching command
         switch(cmdData[k]) {
           // Show a LCD template based on the parameters
           case CMD_LCDTEMPLATE:
             appendResponse(CMD_LCDTEMPLATE);
             // Syntax checking
             if (!isFieldSeparator(cmdData[++k])) {
               syntaxCheck(COMMAND_MISSINGSEPARATOR);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             } // Check for separator
             // We expect the next paramter is the template ID
             value = charsToInt(++k, PARM_FIELDID_LEN);
             // Check if the template ID exceeds the max number of templates
             if(value > MAX_TEMPLATES) {
               syntaxCheck(COMMAND_WRONG_TEMPLATE);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             } // Error wrong template ID
             // Saves the template ID in the template class
             // And initalises the display parameters
             mTemplate.id = value;
             maxFields = mTemplate.createDisplay();
             // Initialises the field counter
             z = 0;
             // Update the command string pointer to the next separator
             k = nextFieldSeparator(k);
             #ifdef __DEBUG
             Serial1 << "maxFields=" << maxFields << " k=" << k << endl;
             #endif
             // Clear the display before showing another template
             mTemplate.cleanDisplay();
             // Now we start processing the fields populating the template class
             while(z < maxFields) {
               bool stopLoop = false;
               #ifdef __DEBUG
               Serial1 << "z=" << z << endl;
               #endif
               // Syntax checking
               if (!isFieldSeparator(cmdData[k])) {
                 syntaxCheck(COMMAND_MISSINGSEPARATOR);
                 k = nextCommandSeparator(k);
                 z = maxFields; // force the exit conditions
                 stopLoop = true;
               }
               // Start processing the strings only if the stop loop condition
               // is false (no error)
               if(!stopLoop) {
                 // We expect the next parameter is the field string
                 cmd.stringValue = charsToString(k);
                 syntaxCheck(COMMAND_OK);
                 #ifdef __DEBUG
                 Serial1 << "Template string " << cmd.stringValue << endl;
                 #endif
                 // Display the message string on LCD
                 mTemplate.updateDisplay(cmd.stringValue, z);
                 // Update the command string pointer to the next separator
                 // We start from the character point immediately after the
                 // previous field separator found in the loop
                 k = nextFieldSeparator(k+1);
                 z++; // next field
               } // If stop loop is not set
             } // While all fields are processes (or exiting on error)
             ackMaster();
             break;
           // Show a string on the display.
           case CMD_DISPLAY:
             appendResponse(CMD_DISPLAY);
             // Syntax checking
             if (!isFieldSeparator(cmdData[++k])) {
               syntaxCheck(COMMAND_MISSINGSEPARATOR);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             }
             // We expect the next paramter is row expressed in integer format
             value = charsToInt(++k, PARM_INTEGER_LEN);
             if (value < LCDROWS) {
               syntaxCheck(COMMAND_OK);
               cmd.intValue[0] = value;
             } // No errors
             else {
               syntaxCheck(COMMAND_OUT_OF_RANGE);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             } // Error out of range
             // Update the command string pointer to the next separator
             k = nextFieldSeparator(k);
             // Syntax checking
             if (!isFieldSeparator(cmdData[k])) {
               syntaxCheck(COMMAND_MISSINGSEPARATOR);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             }
             // We expect the next paramter is column expressed in integer format
             value = charsToInt(++k, PARM_INTEGER_LEN);
             if (value < LCDCHARS) {
               syntaxCheck(COMMAND_OK);
               cmd.intValue[1] = value;
             } // No errors
             else {
               syntaxCheck(COMMAND_OUT_OF_RANGE);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             } // Error out of range
             // Update the command string pointer to the next separator
             k = nextFieldSeparator(k);
             // Syntax checking
             if (!isFieldSeparator(cmdData[k])) {
               syntaxCheck(COMMAND_MISSINGSEPARATOR);
               ackMaster();
               k = nextCommandSeparator(k);
               break;
             }
             // We expect the next paramter is the data string
             cmd.stringValue = charsToString(k);
             syntaxCheck(COMMAND_OK);
             // Display the message string on LCD
             message(cmd.stringValue, cmd.intValue[1], cmd.intValue[0]);
             ackMaster();
             break;
             // Enable a status on the control panel (mainly a probe setting).
             // The details of the object to enable are specified in the subcommand
             case CMD_ENABLE:
               appendResponse(CMD_ENABLE);
               // Search for subcommands
               if (!isFieldSeparator(cmdData[++k])) {
                 syntaxCheck(COMMAND_MISSINGSEPARATOR);
                 ackMaster();
                 k = nextCommandSeparator(k);
                 break;
               } // Search subcommands
               cmd.subcommand[0] = cmdData[++k];
               // Manage the subcommands parameter
               switch(cmd.subcommand[0]) {
                 // Enable / disable the stethoscope probe control panel settings
                 case S_STETHOSCOPE:
                   appendResponse(S_STETHOSCOPE);
                   // Check for subcommand separator
                   if (!isFieldSeparator(cmdData[++k])) {
                       syntaxCheck(COMMAND_MISSINGSEPARATOR);
                       ackMaster();
                       k = nextCommandSeparator(k);
                       break;
                   } // check for separator
                   if (!setStethoscopeStatus(++k))
                       syntaxCheck(COMMAND_STETHOSCOPE_PARAMERROR);
                   else
                       syntaxCheck(COMMAND_OK);
                   ackMaster();
                   k = nextCommandSeparator(k);
                   break;
                 // Enable / disable the ECG probe control panel settings
                 case S_ECG:
                   appendResponse(S_ECG);
                   // Check for subcommand separator
                   if (!isFieldSeparator(cmdData[++k])) {
                       syntaxCheck(COMMAND_MISSINGSEPARATOR);
                       ackMaster();
                       k = nextCommandSeparator(k);
                       break;
                   } // check for separator
                   if (!setECGStatus(++k))
                       syntaxCheck(COMMAND_ECG_PARAMERROR);
                   else
                       syntaxCheck(COMMAND_OK);
                   ackMaster();
                   k = nextCommandSeparator(k);
                   break;
                 // Enable / disable the Blood Pressure probe control panel settings
                 case S_PRESSURE:
                   appendResponse(S_PRESSURE);
                   // Check for subcommand separator
                   if (!isFieldSeparator(cmdData[++k])) {
                       syntaxCheck(COMMAND_MISSINGSEPARATOR);
                       ackMaster();
                       k = nextCommandSeparator(k);
                       break;
                   } // check for separator
                   if (!setPressureStatus(++k))
                       syntaxCheck(COMMAND_PRESSURE_PARAMERROR);
                   else
                       syntaxCheck(COMMAND_OK);
                   ackMaster();
                   k = nextCommandSeparator(k);
                   break;
                 // Enable / disable the Body Temperature probe control panel settings
                 case S_BODYTEMP:
                   appendResponse(S_BODYTEMP);
                   // Check for subcommand separator
                   if (!isFieldSeparator(cmdData[++k])) {
                       syntaxCheck(COMMAND_MISSINGSEPARATOR);
                       ackMaster();
                       k = nextCommandSeparator(k);
                       break;
                   } // check for separator
                   if (!setBodyTempStatus(++k))
                       syntaxCheck(COMMAND_BODYTEMP_PARAMERROR);
                   else
                       syntaxCheck(COMMAND_OK);
                   ackMaster();
                   k = nextCommandSeparator(k);
                   break;
                 // Enable / disable the Heart Beat probe control panel settings
                 case S_HEARTBEAT:
                   appendResponse(S_HEARTBEAT);
                   // Check for subcommand separator
                   if (!isFieldSeparator(cmdData[++k])) {
                       syntaxCheck(COMMAND_MISSINGSEPARATOR);
                       ackMaster();
                       k = nextCommandSeparator(k);
                       break;
                   } // check for separator
                   if (!setHeartBeatStatus(++k))
                       syntaxCheck(COMMAND_HEARTBEAT_PARAMERROR);
                   else
                       syntaxCheck(COMMAND_OK);
                   ackMaster();
                   k = nextCommandSeparator(k);
                   break;
                 // Subcommand unknown
                 default:
                     syntaxCheck(PARSER_SUBCOMMAND_UNKNOWN);
                     ackMaster();
                     break;
             } // Subcommands for the Enable command
             break;
             // Show the global info on the control panel display
             case CMD_INFO:
               appendResponse(CMD_INFO);
               ackMaster();
             break;
             // Executes a test cycle of the control panel
             case CMD_TEST:
               appendResponse(CMD_TEST);
               ackMaster();
             break;
             // If no command is recognised, do nothing
             default:
               break;
         } // Command processing switch case
         j = CMD_CHARLEN;
       } // Check with the current command character
     } // Loop on command characters (syntax checking)
     k++;
   } // main while loop
   i = 0;
 }
int readline (int readch, char * buffer, int len)
Read a full line buffer from serial.
readch The character read from serial
Parameters
buffer The char buffer pointer
len the las position read in the buffer
Returns
-1 of the number of read characers on the line (if the line ends)
Definition at line 419 of file Meditech_ChipKitControlPanel.pde.
Referenced by checkSerial().
{
   static int pos = 0;
   int rpos;
   if (readch > 0) {
     switch (readch) {
       case '\n': // Ignore new-lines
         break;
       case '\r': // Return on CR
         rpos = pos;
         pos = 0;  // Reset position index ready for next time
         return rpos;
       default:
         if (pos < len-1) {
           buffer[pos++] = readch;
           buffer[pos] = 0;
         }
     }
   }
   // No end of line has been found, so return -1.
   return -1;
 }
bool setBodyTempStatus (int startChar)
Set the body temperature status flag and initialises the display parameters if needed.
Parameters
startChar initial character in the command string
Todo:
Implement this function
Definition at line 1191 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
Referenced by parser().
{
   int res = 0;
   String extract = "";
   extract.concat(cmdData[startChar]);
   res = extract.toInt();
   if(res == 0)
     return false;
   else
     return true;
 }
bool setECGStatus (int startChar)
Set the ECG status flag and initialises the display parameters if needed.
Todo:
Implement this function
Definition at line 1151 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
Referenced by parser().
{
   int res = 0;
   String extract = "";
   extract.concat(cmdData[startChar]);
   res = extract.toInt();
   if(res == 0)
     return false;
   else
     return true;
 }
void setFanSpeed (float temp)
Set the fan speed based on the actual temperature.
The fan speed is mapped on the current temperature scaled to the PWM range values. Note that any PWM frequency under MIN_FAN_SPEED should not used at is has no effect (the motor don't start)
Note
This function sets manually the fan speed based on the internal temperature sensor. To use this function the interrupt timer fanSpeedRegulationTaskID should be disabled before.
The filtered temperature to control the out-of-range values
Definition at line 362 of file Meditech_ChipKitControlPanel.pde.
References FAN_SPEED, MAX_FANSPEED, MAX_TEMP, MIN_FANSPEED, and MIN_TEMP.
Referenced by setup(), and testFanSpeed().
{
   float filteredTemp;
   // Check the temperature range
   if (temp < MIN_TEMP)
     filteredTemp = MIN_TEMP;
   else
     if (temp > MAX_TEMP)
       filteredTemp = MAX_TEMP;
       else
         filteredTemp = temp;
   int pwmSpeed = map(temp, MIN_TEMP, MAX_TEMP, MIN_FANSPEED, MAX_FANSPEED);
   SoftPWMServoPWMWrite(FAN_SPEED, pwmSpeed);
 }
int setFanSpeed (int freq)
Set the fan speed at the desired PWM frequency.
The PWM frequency should be included between the min and max fan speed values. If these values are outside the limits the fan is set to off
Fan speed PWM frequency, initialised to the stop status
Definition at line 387 of file Meditech_ChipKitControlPanel.pde.
References FAN_SPEED, MAX_FANSPEED, and STOP_FAN.
{
   int pwmFreq = STOP_FAN;
   // Check if the freq is a correct value
   if( (freq >= STOP_FAN) && (freq <= MAX_FANSPEED) ) {
     pwmFreq = freq;
   }
   // Set the current fan speed
   SoftPWMServoPWMWrite(FAN_SPEED, pwmFreq);
   return pwmFreq;
 }
bool setHeartBeatStatus (int startChar)
Set the heart beat status flag and initialises the display parameters if needed.
The function does not need the number of characters parameters as the status ia boolean single character for the flag
Parameters
startChar initial character in the command string
Todo:
Implement this function
Definition at line 1214 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
Referenced by parser().
{
   int res = 0;
   String extract = "";
   extract.concat(cmdData[startChar]);
   res = extract.toInt();
   if(res == 0)
     return false;
   else
     return true;
 }
bool setPressureStatus (int startChar)
Set the bood pressure status flag and initialises the display parameters if needed.
Parameters
startChar initial character in the command string
Todo:
Implement this function
Definition at line 1171 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
Referenced by parser().
{
   int res = 0;
   String extract = "";
   extract.concat(cmdData[startChar]);
   res = extract.toInt();
   if(res == 0)
     return false;
   else
     return true;
 }
bool setStethoscopeStatus (int startChar)
Set the stethoscope status flag and initialises the display parameters if needed.
Parameters
startChar initial character in the command string
Todo:
Implement this function
Definition at line 1132 of file Meditech_ChipKitControlPanel.pde.
References cmdData.
Referenced by parser().
{
   int res = 0;
   String extract = "";
   extract.concat(cmdData[startChar]);
   res = extract.toInt();
   if(res == 0)
     return false;
   else
     return true;
 }
void setup ()
Initialisation method.
Loaded once at power-on the setup() method presets the parameters of the application and initializes the ChipKit board to its initial conditions. The startup conditions assumes that the Meditech lid is closed. If not, after a couple of seconds the alarm starts immediately.
Definition at line 87 of file Meditech_ChipKitControlPanel.pde.
References Temperature::CalcTemp(), CAMERA_STATUS, ECG_STATUS, fanSpeedRegulation(), isLidStatusChanged(), lcd(), LCDCHARS, LCDROWS, LIDCLOSED, LIDSTATUS, lidStatus, SERIAL_SPEED, setFanSpeed(), showTemp(), STETHOSCOPE_STATUS, STOP_FAN, TASK_UPDATEDISPLAY, TEMP_SENSOR, testFanSpeed(), testStatusLED(), updateDispalyTaskID, updateDisplay(), and welcome().
              {
   Serial1.begin(SERIAL_SPEED);
   // Initializes the Lid status switch pin
   pinMode(LIDSTATUS, INPUT);
   lidStatus = LIDCLOSED;
   pinMode(ECG_STATUS, OUTPUT);
   pinMode(STETHOSCOPE_STATUS, OUTPUT);
   pinMode(CAMERA_STATUS, OUTPUT);
   digitalWrite(ECG_STATUS, HIGH);
   digitalWrite(STETHOSCOPE_STATUS, HIGH);
   digitalWrite(CAMERA_STATUS, HIGH);
   // Initializes the LCD library
   lcd.begin(LCDCHARS, LCDROWS);
   // Turn LCD On
   lcd.display();
   // Initialisation string
   welcome();
   // Test the LEDs
   testStatusLED();
   // Read the actual temperature
   internalTemp.CalcTemp(analogRead(TEMP_SENSOR));
   // Shows the actual internal temperature
   showTemp();
   // Start the fan to stopped state
   setFanSpeed(STOP_FAN);
   // Test LEDs on startup
   testStatusLED();
   // Test the fan variable speed
   testFanSpeed();
   // Set and start the timer for lid status
   attachCoreTimerService(isLidStatusChanged);
   // Set and start the timer for fan cooler speed regulation
   attachCoreTimerService(fanSpeedRegulation);
   // Create the display update task.
   // This task updates automatically only the reserved display
   // areas, i.e. the temperature monitor and other information.
   updateDispalyTaskID = createTask(updateDisplay, TASK_UPDATEDISPLAY, TASK_ENABLE, NULL);
 }
void showTemp ()
shows the actual internal temperature on the top right corner.
This is a display-only method.
Definition at line 200 of file Meditech_ChipKitControlPanel.pde.
References _CELSIUS, Temperature::Celsius(), lcd(), and LCDTOPROW.
Referenced by setup(), and tempMonitor().
                 {
   lcd.setCursor(14, LCDTOPROW);
   lcd << internalTemp.Celsius() << _CELSIUS;
 }
void strFloat (float val, unsigned int precision)
Convert a floating value to string with the specified precision.
As a matter of fact the ouput functions (string, serial, stream library etc.) does not represent in a flexible way the floating point values. This function calculates the right string with the desidred decimal precision sending to serial with the streaming library.
Calculating the decimal value the function add the number of leading zeroes searching for all the decimal places before the first non-zero number.
The loop for the leading zeroes grows by a factor 10 between 0 (no leading zeroes needed) and precision (all zeroes, no decimal numbers).
Note
Precision is represented by 1 followed by the number of zeroes for the desired number of decimial places.
example: strLong(3.1415, 100) prints 3.14 (two decimal places)
Parameters
val the floating value to represent
precision the decimal precision
Definition at line 1107 of file Meditech_ChipKitControlPanel.pde.
{
     int i;
     unsigned int frac;
     if(val >= 0)
       frac = (val - int(val)) * precision;
     else
       frac = (int(val)- val ) * precision;
     Serial1 << int(val) << ".";
     for (i = 1; i <= precision; i += i * 10)
         if (frac < i)
             Serial1 << "0";
     Serial1 << frac;
 }
void syntaxCheck (int errCode)
Append the error code to the master response message string.
Parameters
errCode the error code from the command
Definition at line 983 of file Meditech_ChipKitControlPanel.pde.
References appendResponse().
Referenced by parser().
{
   appendResponse(errCode);
 }
void tempMonitor ()
Update the internal temperature from the sensor and update the display.
Definition at line 188 of file Meditech_ChipKitControlPanel.pde.
References Temperature::CalcTemp(), showTemp(), and TEMP_SENSOR.
Referenced by updateDisplay().
                    {
   // Read the actual temperature
   internalTemp.CalcTemp(analogRead(TEMP_SENSOR));
   showTemp();
 }
void testFanSpeed ()
Variable fan speed test cycle.
Definition at line 338 of file Meditech_ChipKitControlPanel.pde.
References MAX_FANSPEED, MIN_FANSPEED, and setFanSpeed().
Referenced by setup().
                     {
  for(int j = MIN_FANSPEED; j <= MAX_FANSPEED; j += 10) {
    setFanSpeed(j);
    delay(500);
  }
  for(int j = MAX_FANSPEED; j <= MIN_FANSPEED; j -= 10) {
    setFanSpeed(j);
    delay(500);
  }
 }
void testStatusLED ()
Show the status led blinking for a cycle to test that all are working.
Definition at line 317 of file Meditech_ChipKitControlPanel.pde.
References CAMERA_STATUS, ECG_STATUS, and STETHOSCOPE_STATUS.
Referenced by setup().
                      {
   digitalWrite(ECG_STATUS, LOW);
   delay(200);
   digitalWrite(STETHOSCOPE_STATUS, LOW);
   delay(200);
   digitalWrite(CAMERA_STATUS, LOW);
   delay(200);
   digitalWrite(ECG_STATUS, HIGH);
   delay(200);
   digitalWrite(STETHOSCOPE_STATUS, HIGH);
   delay(200);
   digitalWrite(CAMERA_STATUS, HIGH);
   delay(200);
 }
void updateDisplay (int id, void * tptr)
Periodically update the display.
This is a task callback function
Definition at line 161 of file Meditech_ChipKitControlPanel.pde.
References tempMonitor().
Referenced by setup().
{
  tempMonitor();
 }
void welcome ()
Welcome message shown at device power-on.
Definition at line 243 of file Meditech_ChipKitControlPanel.pde.
References _BD, _BUILD, _MEDITECH, _SPACING, _VERSION, build, lcd(), LCDBOTTOMROW, LCDMESSAGE_DELAY, LCDTOPROW, project, and version.
Referenced by setup().
                {
   lcd.clear();
   lcd.setCursor(0, LCDTOPROW);
   lcd << project();
   lcd.setCursor(0, LCDBOTTOMROW);
   lcd << _VERSION << _SPACING << version() << _SPACING << _BUILD << _SPACING << build();
   delay(LCDMESSAGE_DELAY);
   lcd.clear();
   lcd.setCursor(0, 0);
   lcd.print(_BD);
   lcd.setCursor(0, 1);
   lcd.print(_MEDITECH);
   delay(2500);
   lcd.clear();
 }
Variable Documentation
command cmd
Parser command structure.
Definition at line 66 of file Meditech_ChipKitControlPanel.pde.
char cmdData[1024] static
Unparsed Command String.
cmdData is the string after syntax checking. The string can contain one or more commands. When the command string is sent to the parser this value contains the command sequence. When the this string is empy all the commands has been processed and the system is ready to receive a new command.
Definition at line 78 of file Meditech_ChipKitControlPanel.pde.
Referenced by charsToFloat(), charsToLong(), charsToString(), checkSerial(), nextCommandSeparator(), nextFieldSeparator(), parser(), setBodyTempStatus(), setECGStatus(), setHeartBeatStatus(), setPressureStatus(), and setStethoscopeStatus().
Temperature internalTemp
Internal temperature sensor class instance.
Definition at line 52 of file Meditech_ChipKitControlPanel.pde.
volatile boolean lidStatus
Current lid status. The variable is declared volatile as it is used by the IRQ callback function too.
Definition at line 60 of file Meditech_ChipKitControlPanel.pde.
Referenced by isLidStatusChanged(), loop(), and setup().
int pValue = 0
Initial potentiometer value.
Definition at line 55 of file Meditech_ChipKitControlPanel.pde.
int updateDispalyTaskID
The update display task id (assigned on setup)
Definition at line 63 of file Meditech_ChipKitControlPanel.pde.
Referenced by setup().