Meditech control panel software: LCDTemplates Class Reference
LCDTemplates Class Reference
#include "LCDTemplates.h"
Public Member Functions
LCDTemplates (AlphaLCD myLCD)
Class constructor.
int createDisplay ()
Create the full display view parameters.
void updateDisplay (String val, int fieldID)
Update the variable content field(s) only.
void cleanDisplay ()
Clean che LCD display area.
Public Attributes
int id
LCDTemplateField fields
Private Attributes
AlphaLCD mLcd
Detailed Description
Definition at line 144 of file LCDTemplates.h.
Constructor & Destructor Documentation
LCDTemplates::LCDTemplates (AlphaLCD myLCD)
Class constructor.
Definition at line 14 of file LCDTemplates.cpp.
References mLcd.
{
   mLcd = myLCD;
 }
Member Function Documentation
void LCDTemplates::cleanDisplay ()
Clean che LCD display area.
Definition at line 144 of file LCDTemplates.cpp.
References mLcd.
Referenced by parser().
{
   mLcd.clear();
 }
int LCDTemplates::createDisplay ()
Create the full display view parameters.
This method should be called only when the template ID has already been set.
Returns
The number of fields of the selected template
Definition at line 26 of file LCDTemplates.cpp.
References BLOOD_MAX, BLOOD_MAXVAL, BLOOD_MIN, BLOOD_MINVAL, BLOOD_TITLE, BLOOD_WAIT, BLOODPRESS_FIELDS, LCDTemplateField::col, DEFAULT_FIELDS, DEFAULT_STATUS, DEFAULT_TITLE, DEFAULT_VERSION, ECG_FIELDS, ECG_STATUS, ECG_STATUSFLAG, ECG_TITLE, fields, HEARTBEAT_AVERAGE, HEARTBEAT_AVERAGEVAL, HEARTBEAT_FIELDS, HEARTBEAT_SPOT, HEARTBEAT_SPOTVAL, HEARTBEAT_TITLE, INFO_DATE, INFO_FIELDS, INFO_GPS, INFO_RPM, INFO_TIME, INFO_TITLE, LCDTemplateField::row, STET_GAIN, STET_GAINVAL, STET_TITLE, STETHOSCOPE_FIELDS, TEMPERATURE_AVERAGE, TEMPERATURE_AVERAGEVAL, TEMPERATURE_FIELDS, TEMPERATURE_SPOT, TEMPERATURE_SPOTVAL, TEMPERATURE_TITLE, TEST_FIELDS, TEST_STATUS, TEST_TITLE, TID_BLOODPRESS, TID_DEFAULT, TID_ECG, TID_HEARTBEAT, TID_INFO, TID_STETHOSCOPE, TID_TEMPERATURE, and TID_TEST.
Referenced by parser().
{
   int numFields;
   switch(id) {
     case TID_STETHOSCOPE:
       fields.row[STET_TITLE] = 0;
       fields.col[STET_TITLE] = 0;
       fields.row[STET_GAIN] = 1;
       fields.col[STET_GAIN] = 0;
       fields.row[STET_GAINVAL] = 1;
       fields.col[STET_GAINVAL] = 12;
       numFields = STETHOSCOPE_FIELDS;
     break;
     case TID_BLOODPRESS:
       fields.row[BLOOD_TITLE] = 0;
       fields.col[BLOOD_TITLE] = 0;
       fields.row[BLOOD_WAIT] = 1;
       fields.col[BLOOD_WAIT] = 16;
       fields.row[BLOOD_MIN] = 1;
       fields.col[BLOOD_MIN] = 0;
       fields.row[BLOOD_MINVAL] = 1;
       fields.col[BLOOD_MINVAL] = 3;
       fields.row[BLOOD_MAX] = 1;
       fields.col[BLOOD_MAX] = 7;
       fields.row[BLOOD_MAXVAL] = 1;
       fields.col[BLOOD_MAXVAL] = 9;
       numFields = BLOODPRESS_FIELDS;
     break;
     case TID_HEARTBEAT:
       fields.row[HEARTBEAT_TITLE] = 0;
       fields.col[HEARTBEAT_TITLE] = 0;
       fields.row[HEARTBEAT_SPOT] = 1;
       fields.col[HEARTBEAT_SPOT] = 0;
       fields.row[HEARTBEAT_SPOTVAL] = 1;
       fields.col[HEARTBEAT_SPOTVAL] = 5;
       fields.row[HEARTBEAT_AVERAGE] = 1;
       fields.col[HEARTBEAT_AVERAGE] = 10;
       fields.row[HEARTBEAT_AVERAGEVAL] = 1;
       fields.col[HEARTBEAT_AVERAGEVAL] = 15;
       numFields = HEARTBEAT_FIELDS;
     break;
     case TID_TEMPERATURE:
       fields.row[TEMPERATURE_TITLE] = 0;
       fields.col[TEMPERATURE_TITLE] = 0;
       fields.row[TEMPERATURE_SPOT] = 1;
       fields.col[TEMPERATURE_SPOT] = 0;
       fields.row[TEMPERATURE_SPOTVAL] = 1;
       fields.col[TEMPERATURE_SPOTVAL] = 5;
       fields.row[TEMPERATURE_AVERAGE] = 1;
       fields.col[TEMPERATURE_AVERAGE] = 10;
       fields.row[TEMPERATURE_AVERAGEVAL] = 1;
       fields.col[TEMPERATURE_AVERAGEVAL] = 15;
       numFields = TEMPERATURE_FIELDS;
     break;
     case TID_ECG:
       fields.row[ECG_TITLE] = 0;
       fields.col[ECG_TITLE] = 0;
       fields.row[ECG_STATUS] = 1;
       fields.col[ECG_STATUS] = 0;
       fields.row[ECG_STATUSFLAG] = 1;
       fields.col[ECG_STATUSFLAG] = 7;
       numFields = ECG_FIELDS;
     break;
     case TID_TEST:
       fields.row[TEST_TITLE] = 0;
       fields.col[TEST_TITLE] = 0;
       fields.row[TEST_STATUS] = 1;
       fields.col[TEST_STATUS] = 0;
       numFields = TEST_FIELDS;
     break;
     case TID_INFO:
       fields.row[INFO_TITLE] = 0;
       fields.col[INFO_TITLE] = 0;
       fields.row[INFO_RPM] = 1;
       fields.col[INFO_RPM] = 16;
       fields.row[INFO_DATE] = 0;
       fields.col[INFO_DATE] = 4;
       fields.row[INFO_TIME] = 0;
       fields.col[INFO_TIME] = 9;
       fields.row[INFO_GPS] = 1;
       fields.col[INFO_GPS] = 0;
       numFields = INFO_FIELDS;
     break;
     case TID_DEFAULT:
       fields.row[DEFAULT_TITLE] = 0;
       fields.col[DEFAULT_TITLE] = 0;
       fields.row[DEFAULT_VERSION] = 1;
       fields.col[DEFAULT_VERSION] = 0;
       fields.row[DEFAULT_STATUS] = 1;
       fields.col[DEFAULT_STATUS] = 10;
       numFields = DEFAULT_FIELDS;
     break;
   }
   return numFields;
 }
void LCDTemplates::updateDisplay (String val, int fieldID)
Update the variable content field(s) only.
This method should be called every time the field content of a variable is updated. It affects only the data content fields. To recreate the entire display the createDisplay() method should be called. When the method is called, the class field value is updated after the value conversion.
Parameters
val The string to update
field The field ID
Definition at line 136 of file LCDTemplates.cpp.
References LCDTemplateField::col, fields, mLcd, and LCDTemplateField::row.
Referenced by parser().
{
   mLcd.setCursor(fields.col[fieldID], fields.row[fieldID]);
   mLcd << val;
 }
Member Data Documentation
LCDTemplateField LCDTemplates::fields
Definition at line 151 of file LCDTemplates.h.
Referenced by createDisplay(), and updateDisplay().
int LCDTemplates::id
Definition at line 150 of file LCDTemplates.h.
Referenced by parser().
AlphaLCD LCDTemplates::mLcd private
Definition at line 153 of file LCDTemplates.h.
Referenced by cleanDisplay(), LCDTemplates(), and updateDisplay().
The documentation for this class was generated from the following files:
/Volumes/John Doe/Development Projects/Meditech SciFi/SourcesRepositories/chipkit_serial_pi/Meditech_ChipKitControlPanel/LCDTemplates.h
/Volumes/John Doe/Development Projects/Meditech SciFi/SourcesRepositories/chipkit_serial_pi/Meditech_ChipKitControlPanel/LCDTemplates.cpp